In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/data_redirects.csv')

In [4]:
df

,flightWeek,OriginAirport,DestinationAirport,OriginCountry,DestinationCountry,mainCarrier,isConnectingFlight,isEWRoute,Market,UserCountryCode,...,kind,TripLengthNights,TravelHorizonDays,RedirectsCount,Revenue,Segments,ODPax,TripPax,weekOfYear,Average_FlightFare
0,2024-W24,ALC,OPO,ES,PT,FR,0,0,ES,ES,...,RETURN,4.0,41,9,3914.87,66,18,33,2024-W18,59.316212
1,2024-W31,LTN,JMK,GB,GR,U2,1,0,UK,GB,...,RETURN,4.0,89,1,610.91,4,2,2,2024-W18,152.727500
2,2024-W18,TSR,BCN,RO,ES,H4,1,0,UK,RO,...,RETURN,3.0,3,2,711.19,4,4,2,2024-W18,177.797500
3,2024-W30,NTE,PMO,FR,IT,TO,0,0,FR,FR,...,RETURN,14.0,78,4,4406.40,30,8,15,2024-W18,146.880000
4,2024-W31,FRA,MLA,DE,MT,LH,0,0,DE,DE,...,RETURN,7.0,93,15,10398.57,58,30,29,2024-W18,179.285690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2024-W31,BLQ,SKP,IT,MK,W6,0,0,AU,AU,...,ONE_WAY,NaN,92,2,483.27,4,2,4,2024-W18,120.817500
1048571,2024-W29,BRU,KGS,BE,GR,SN,0,0,BE,BE,...,RETURN,7.0,80,1,1539.60,4,2,2,2024-W18,384.900000
1048572,2024-W22,GOT,MHD,SE,IR,TK,1,0,SE,SE,...,RETURN,30.0,33,1,3551.05,6,2,3,2024-W18,591.841667
1048573,2024-W34,MXP,BEG,IT,RS,JU,0,0,IT,AT,...,ONE_WAY,NaN,115,1,90.11,1,1,1,2024-W18,90.110000
1048574,2024-W21,NRN,PSR,DE,IT,FR,0,0,DE,DE,...,RETURN,4.0,18,1,196.98,6,2,3,2024-W18,32.830000

In [5]:
df.isnull().sum().sort_values(ascending=False)

TripLengthNights      420652
UserCountryCode          469
mainCarrier               77
Market                     8
flightWeek                 0
weekOfYear                 0
TripPax                    0
ODPax                      0
Segments                   0
Revenue                    0
RedirectsCount             0
TravelHorizonDays          0
cabinClass                 0
kind                       0
OriginAirport              0
isEWRoute                  0
isConnectingFlight         0
DestinationCountry         0
OriginCountry              0
DestinationAirport         0
Average_FlightFare         0
dtype: int64

In [10]:
df

,flightWeek,OriginAirport,DestinationAirport,OriginCountry,DestinationCountry,mainCarrier,isConnectingFlight,isEWRoute,Market,UserCountryCode,...,kind,TripLengthNights,TravelHorizonDays,RedirectsCount,Revenue,Segments,ODPax,TripPax,weekOfYear,Average_FlightFare
0,2024-W24,ALC,OPO,ES,PT,FR,0,0,ES,ES,...,RETURN,4.0,41,9,3914.87,66,18,33,2024-W18,59.316212
1,2024-W31,LTN,JMK,GB,GR,U2,1,0,UK,GB,...,RETURN,4.0,89,1,610.91,4,2,2,2024-W18,152.727500
2,2024-W18,TSR,BCN,RO,ES,H4,1,0,UK,RO,...,RETURN,3.0,3,2,711.19,4,4,2,2024-W18,177.797500
3,2024-W30,NTE,PMO,FR,IT,TO,0,0,FR,FR,...,RETURN,14.0,78,4,4406.40,30,8,15,2024-W18,146.880000
4,2024-W31,FRA,MLA,DE,MT,LH,0,0,DE,DE,...,RETURN,7.0,93,15,10398.57,58,30,29,2024-W18,179.285690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2024-W31,BLQ,SKP,IT,MK,W6,0,0,AU,AU,...,ONE_WAY,NaN,92,2,483.27,4,2,4,2024-W18,120.817500
1048571,2024-W29,BRU,KGS,BE,GR,SN,0,0,BE,BE,...,RETURN,7.0,80,1,1539.60,4,2,2,2024-W18,384.900000
1048572,2024-W22,GOT,MHD,SE,IR,TK,1,0,SE,SE,...,RETURN,30.0,33,1,3551.05,6,2,3,2024-W18,591.841667
1048573,2024-W34,MXP,BEG,IT,RS,JU,0,0,IT,AT,...,ONE_WAY,NaN,115,1,90.11,1,1,1,2024-W18,90.110000
1048574,2024-W21,NRN,PSR,DE,IT,FR,0,0,DE,DE,...,RETURN,4.0,18,1,196.98,6,2,3,2024-W18,32.830000

In [16]:
missing_values_df = df[df['Market'].isnull()]
missing_values_df

,flightWeek,OriginAirport,DestinationAirport,OriginCountry,DestinationCountry,mainCarrier,isConnectingFlight,isEWRoute,Market,UserCountryCode,...,kind,TripLengthNights,TravelHorizonDays,RedirectsCount,Revenue,Segments,ODPax,TripPax,weekOfYear,Average_FlightFare
211407,2024-W38,LGW,ORY,GB,FR,VY,0,0,NaN,NaN,...,ONE_WAY,NaN,137,1,45.59,1,1,1,2024-W18,45.590000
213226,2024-W26,ZRH,BCN,CH,ES,WK,0,0,NaN,TR,...,ONE_WAY,NaN,55,2,358.38,2,2,2,2024-W18,179.190000
427889,2024-W42,MUC,PMI,DE,ES,EW,0,1,NaN,NaN,...,ONE_WAY,NaN,172,2,138.88,2,2,2,2024-W18,69.440000
640976,2024-W25,FRA,BER,DE,DE,LH,0,0,NaN,NaN,...,ONE_WAY,NaN,51,1,95.99,1,1,1,2024-W18,95.990000
714377,2024-W20,MLA,LHR,MT,GB,KM,0,0,NaN,NaN,...,RETURN,3.0,14,2,1333.62,4,4,2,2024-W18,333.405000
721570,2024-W19,DUS,AGP,DE,ES,EW,0,1,NaN,NaN,...,ONE_WAY,NaN,7,2,645.78,6,2,6,2024-W18,107.630000
748287,2024-W26,ZRH,BCN,CH,ES,VY,0,0,NaN,TR,...,ONE_WAY,NaN,56,1,42.40,1,1,1,2024-W18,42.400000
812315,2024-W19,LCY,ACC,GB,GH,KL,1,0,NaN,NaN,...,RETURN,11.0,7,6,7908.32,18,12,9,2024-W18,439.351111

In [ ]:
n_unique_values = df['Market'].nunique()

print(n_unique_values)

218

In [25]:
df['Market'].unique()

array(['ES', 'UK', 'FR', 'DE', 'OM', 'IT', 'IL', 'UA', 'GR', 'NO', 'BE',
       'AU', 'PT', 'NL', 'TR', 'CZ', 'BG', 'AT', 'US', 'PH', 'SK', 'PL',
       'BR', 'IE', 'CY', 'KZ', 'IN', 'DK', 'SE', 'LU', 'KR', 'KW', 'CH',
       'TN', 'SA', 'CA', 'HK', 'FI', 'AE', 'CN', 'AL', 'RO', 'MA', 'RU',
       'HU', 'JP', 'RS', 'HR', 'NZ', 'EE', 'SI', 'AR', 'SH', 'MX', 'EG',
       'TW', 'ME', 'AF', 'DZ', 'LB', 'JO', 'NG', 'MV', 'IQ', 'VA', 'LT',
       'SO', 'UZ', 'CL', 'MC', 'AM', 'IS', 'GP', 'PK', 'BY', 'MY', 'VN',
       'LV', 'AD', 'PS', 'CO', 'AZ', 'LI', 'MT', 'MD', 'ID', 'GH', 'PE',
       'SG', 'GE', 'TH', 'SC', 'NP', 'ZA', 'GM', 'GG', 'QA', 'BA', 'BD',
       'XK', 'CR', 'KG', 'MK', 'EC', 'MG', 'RE', 'MU', 'CV', 'ML', 'GT',
       'MO', 'SN', 'TG', 'BH', 'KE', 'BJ', 'ET', 'UY', 'MZ', 'CI', 'KY',
       'LY', 'LR', 'PA', 'GI', 'SY', 'TM', 'IR', 'LC', 'GF', 'LK', 'UG',
       'ZW', 'DJ', 'DO', 'KH', 'MR', 'CU', 'SD', 'CM', 'FK', 'HN', 'VE',
       'FJ', 'GD', 'SV', 'NC', 'ZM', 'RW', 'MQ', 'TC', 'AO', 'BS', 'BM',
       'MM', 'AW', 'YT', 'PY', 'MN', 'AS', 'TJ', 'YE', 'TZ', 'BF', 'PF',
       'SL', 'BO', 'PR', 'GN', 'KP', 'VG', 'FO', 'LA', 'SB', 'GL', 'CD',
       'ER', 'BB', 'MP', 'CG', 'DM', 'NI', 'VI', 'TT', 'ST', 'BW', 'WS',
       'AI', 'PM', 'BN', nan, 'TO', 'SS', 'JM', 'AG', 'TV', 'GW', 'BL',
       'BZ', 'GU', 'AQ', 'GA', 'BT', 'CK', 'NR', 'SR', 'TD', 'PG', 'GS',
       'GQ', 'HT', 'WF', 'CC', 'KN', 'SZ', 'CF', 'SX', 'VU', 'BQ'],
      dtype=object)

In [ ]:
# Update value in 'Market' of rows that have missing values and have isEWroute = True

try:
  if 427889 < df.shape[0]:
    df.iloc[427889, df.columns.get_loc('Market')] = "ES"
    print(df.iloc[427889])
except IndexError:
  print("IndexError: Row index out of bounds.")

flightWeek            2024-W42
OriginAirport              MUC
DestinationAirport         PMI
OriginCountry               DE
DestinationCountry          ES
mainCarrier                 EW
isConnectingFlight           0
isEWRoute                    1
Market                      ES
UserCountryCode            NaN
cabinClass             ECONOMY
kind                   ONE_WAY
TripLengthNights           NaN
TravelHorizonDays          172
RedirectsCount               2
Revenue                 138.88
Segments                     2
ODPax                        2
TripPax                      2
weekOfYear            2024-W18
Average_FlightFare       69.44
Name: 427889, dtype: object

In [ ]:
# Update value only if the row index is valid

try:
  if 721570 < df.shape[0]:
    df.iloc[721570, df.columns.get_loc('Market')] = "ES"
    print(df.iloc[721570])
except IndexError:
  print("IndexError: Row index out of bounds.")

flightWeek            2024-W19
OriginAirport              DUS
DestinationAirport         AGP
OriginCountry               DE
DestinationCountry          ES
mainCarrier                 EW
isConnectingFlight           0
isEWRoute                    1
Market                      ES
UserCountryCode            NaN
cabinClass             ECONOMY
kind                   ONE_WAY
TripLengthNights           NaN
TravelHorizonDays            7
RedirectsCount               2
Revenue                 645.78
Segments                     6
ODPax                        2
TripPax                      6
weekOfYear            2024-W18
Average_FlightFare      107.63
Name: 721570, dtype: object

In [ ]:
# Adding GDP per capita column:
# For rows of the column "kind" with the value  "RETURN" add GDP per Capita of "OriginCountry"
# For rows of the column "kind" with the value "ONE_WAY" add GDP per Capita of "DestinationCountry"

def add_gdp_per_capita(row):
  """
  This function adds GDP per capita to a new column based on the kind of flight.

  Args: A single row of the df.

  Returns: series with original row with the added GDP per capita value.
  """
  if row['kind'] == 'RETURN':
    gdp_col = 'OriginCountry'  # Access GDP for origin country on return flights
  else:
    gdp_col = 'DestinationCountry'  # Access GDP for destination country on one-way flights
  gdp_data = {'USA': 63299, 'China': 11700, 'India': 2771, '...': ...}  # Replace with your actual GDP data
  return row.append(pd.Series([gdp_data.get(row[gdp_col])], index=['GDP_Per_Capita']))

# Apply the function to each row and create a new df.
flights_with_gdp = flights.apply(add_gdp_per_capita, axis=1)

print(flights_with_gdp)

In [ ]:
# Checking all the uniqe destination

df["DestinationCountry"].unique()

array(['PT', 'GR', 'ES', 'IT', 'MT', 'AE', 'SE', 'IE', 'CY', 'GB', 'BE',
       'IL', 'TR', 'FR', 'DE', 'PL', 'NO', 'AT', 'CH', 'IS', 'AL', 'RS',
       'HR', 'LT', 'MA', 'ET', 'JO', 'DK', 'IM', 'HU', 'SA', 'NL', 'EE',
       'LB', 'GH', 'KW', 'IR', 'CZ', 'SL', 'EG', 'DZ', 'RO', 'FI', 'AZ',
       'MD', 'ME', 'TN', 'XK', 'NG', 'LV', 'IQ', 'LU', 'BG', 'QA', 'FO',
       'GN', 'BA', 'UZ', 'BH', 'MK', 'SN', 'AM', 'OM', 'SI', 'SK', 'KZ',
       'JE', 'CI', 'GE', 'KG', 'GM', 'BY', 'GI', 'CV', 'TG', 'MR', 'LY',
       'BF', 'TM', 'GW', 'EH', 'ML', 'GG', 'TJ', 'BJ', 'NE', 'SD', 'LR',
       'SY', 'SH'], dtype=object)

In [ ]:
# Get the number of unique origin countries using len

number_of_unique_origins = len(df["DestinationCountry"].unique())

print(number_of_unique_origins)

90

In [ ]:
# Checking all the uniqe origin countries

df["OriginCountry"].unique()

array(['ES', 'GB', 'RO', 'FR', 'DE', 'OM', 'IT', 'IL', 'AT', 'GR', 'NO',
       'EG', 'AE', 'PL', 'PT', 'NL', 'IE', 'TR', 'CZ', 'HR', 'JO', 'SE',
       'LB', 'ME', 'MA', 'DZ', 'BE', 'CY', 'KZ', 'MD', 'DK', 'LU', 'CH',
       'BG', 'EE', 'TN', 'SA', 'FI', 'AL', 'IR', 'HU', 'GE', 'MK', 'IQ',
       'LT', 'SK', 'RS', 'SN', 'NG', 'SI', 'BA', 'KW', 'UZ', 'LV', 'AM',
       'XK', 'FO', 'BH', 'QA', 'IS', 'AZ', 'MT', 'GH', 'GI', 'KG', 'GM',
       'JE', 'CV', 'BY', 'GG', 'ML', 'ET', 'LR', 'SL', 'SD', 'TG', 'MR',
       'TJ', 'BJ', 'IM', 'CI', 'GN', 'LY', 'EH', 'GW', 'BF', 'SY', 'TM',
       'NE'], dtype=object)

In [ ]:
# Get the number of unique origin countries using len

number_of_unique_origins = len(df["OriginCountry"].unique())

print(number_of_unique_origins)

89

In [ ]:
# Find the intersection of unique countries (common countries)

common_countries = set(df['OriginCountry'].unique()) & set(df['DestinationCountry'].unique())

# Count the number of common countries
number_of_common_countries = len(common_countries)

print(number_of_common_countries)

89

In [ ]:
# Get the unique countries from both columns

unique_origins = set(df['OriginCountry'].unique())
unique_destinations = set(df['DestinationCountry'].unique())

destination_only_countries = unique_destinations.difference(unique_origins)

if len(destination_only_countries) == 1:
  only_destination_country = destination_only_countries.pop()
  print(f"Country present only in destinations: {only_destination_country}")
else:
  print("There might be multiple or zero countries present only in destinations.")

Country present only in destinations: SH

In [ ]:
try:
  value = df["DestinationCountry"]["SH"]
  print(value)  # This line will only execute if the key exists
except KeyError:
  print("The country 'SH' is not present in the 'DestinationCountry' column.")

The country 'SH' is not present in the 'DestinationCountry' column.

In [ ]:
# Number of unique ip adress locations

len(df["UserCountryCode"].unique())

213

In [ ]:
# Unique ip adress locations

array = df["UserCountryCode"].unique()
array

array(['ES', 'GB', 'RO', 'FR', 'DE', 'OM', 'IT', 'IL', 'AT', 'GR', 'NO',
       'AU', 'PT', 'NL', 'TR', 'CZ', 'BG', 'PL', 'BE', 'SK', 'BR', 'CY',
       'KZ', 'IN', 'DK', 'SE', 'LU', 'KR', 'KW', 'CH', 'LB', 'IE', 'EE',
       'TN', 'SA', 'CA', 'CN', 'JP', 'FI', 'AE', nan, 'AL', 'UA', 'MA',
       'RU', 'HU', 'RS', 'GE', 'HR', 'XK', 'SI', 'IQ', 'AR', 'NZ', 'DZ',
       'BY', 'LV', 'TW', 'JO', 'ID', 'EG', 'ME', 'AF', 'MX', 'BO', 'NG',
       'US', 'PH', 'LT', 'PK', 'UZ', 'SG', 'CO', 'UY', 'MC', 'MT', 'AM',
       'IS', 'BA', 'BH', 'TH', 'MY', 'AD', 'VN', 'CR', 'AZ', 'LI', 'IR',
       'LY', 'YE', 'MD', 'GH', 'PS', 'SC', 'JE', 'ZA', 'GM', 'SY', 'CV',
       'QA', 'BD', 'CL', 'PA', 'IM', 'MK', 'KH', 'PE', 'EC', 'GT', 'SN',
       'RE', 'GG', 'MU', 'ML', 'GI', 'KG', 'ET', 'KE', 'NI', 'KY', 'UG',
       'LK', 'MV', 'SO', 'CD', 'SL', 'SM', 'LA', 'CG', 'SR', 'WS', 'PY',
       'GF', 'DO', 'GP', 'MR', 'CI', 'BJ', 'CU', 'BT', 'PF', 'GW', 'VE',
       'SV', 'ST', 'FK', 'HN', 'FJ', 'ZW', 'RW', 'NC', 'BM', 'GU', 'MN',
       'NP', 'TJ', 'ZM', 'BF', 'TZ', 'LC', 'SD', 'VC', 'DJ', 'NE', 'GN',
       'GA', 'MM', 'FO', 'AG', 'MZ', 'BQ', 'GL', 'AW', 'VA', 'MQ', 'BB',
       'BS', 'JM', 'LR', 'TT', 'CM', 'CE', 'KN', 'AO', 'TD', 'SX', 'PG',
       'MG', 'BW', 'BN', 'BZ', 'TC', 'CW', 'GD', 'TL', 'TG', 'GQ', 'YT',
       'PR', 'SS', 'MW', 'CK', 'MF', 'TM', 'VI', 'VG', 'KM', 'HT', 'PW',
       'MS', 'AI', 'BI', 'GY'], dtype=object)

In [ ]:
# Create an dictionary that includes the ip adress locations as key and the corresponding country as values. if the ip location is a country itself, please return the country as a value nonetheless

ip_country_dict = {
    'ES': 'Spain', 'GB': 'United Kingdom', 'RO': 'Romania', 'FR': 'France', 'DE': 'Germany',
    'OM': 'Oman', 'IT': 'Italy', 'IL': 'Israel', 'AT': 'Austria', 'GR': 'Greece', 'NO': 'Norway',
    'AU': 'Australia', 'PT': 'Portugal', 'NL': 'Netherlands', 'TR': 'Turkey', 'CZ': 'Czech Republic',
    'BG': 'Bulgaria', 'PL': 'Poland', 'BE': 'Belgium', 'SK': 'Slovakia', 'BR': 'Brazil', 'CY': 'Cyprus',
    'KZ': 'Kazakhstan', 'IN': 'India', 'DK': 'Denmark', 'SE': 'Sweden', 'LU': 'Luxembourg', 'KR': 'South Korea',
    'KW': 'Kuwait', 'CH': 'Switzerland', 'LB': 'Lebanon', 'IE': 'Ireland', 'EE': 'Estonia', 'TN': 'Tunisia',
    'SA': 'Saudi Arabia', 'CA': 'Canada', 'CN': 'China', 'JP': 'Japan', 'FI': 'Finland', 'AE': 'United Arab Emirates',
    'AL': 'Albania', 'UA': 'Ukraine', 'MA': 'Morocco', 'RU': 'Russia', 'HU': 'Hungary', 'RS': 'Serbia',
    'GE': 'Georgia', 'HR': 'Croatia', 'XK': 'Kosovo', 'SI': 'Slovenia', 'IQ': 'Iraq', 'AR': 'Argentina',
    'NZ': 'New Zealand', 'DZ': 'Algeria', 'BY': 'Belarus', 'LV': 'Latvia', 'TW': 'Taiwan', 'JO': 'Jordan',
    'ID': 'Indonesia', 'EG': 'Egypt', 'ME': 'Montenegro', 'AF': 'Afghanistan', 'MX': 'Mexico', 'BO': 'Bolivia',
    'NG': 'Nigeria', 'US': 'United States', 'PH': 'Philippines', 'LT': 'Lithuania', 'PK': 'Pakistan',
    'UZ': 'Uzbekistan', 'SG': 'Singapore', 'CO': 'Colombia', 'UY': 'Uruguay', 'MC': 'Monaco', 'MT': 'Malta',
    'AM': 'Armenia', 'IS': 'Iceland', 'BA': 'Bosnia and Herzegovina', 'BH': 'Bahrain', 'TH': 'Thailand',
    'MY': 'Malaysia', 'AD': 'Andorra', 'VN': 'Vietnam', 'CR': 'Costa Rica', 'AZ': 'Azerbaijan', 'LI': 'Liechtenstein',
    'IR': 'Iran', 'LY': 'Libya', 'YE': 'Yemen', 'MD': 'Moldova', 'GH': 'Ghana', 'PS': 'Palestine',
    'SC': 'Seychelles', 'JE': 'Jersey', 'ZA': 'South Africa', 'GM': 'Gambia', 'SY': 'Syria', 'CV': 'Cape Verde',
    'QA': 'Qatar', 'BD': 'Bangladesh', 'CL': 'Chile', 'PA': 'Panama', 'IM': 'Isle of Man', 'MK': 'North Macedonia',
    'KH': 'Cambodia', 'PE': 'Peru', 'EC': 'Ecuador', 'GT': 'Guatemala', 'SN': 'Senegal', 'RE': 'Reunion',
    'GG': 'Guernsey', 'MU': 'Mauritius', 'ML': 'Mali', 'GI': 'Gibraltar', 'KG': 'Kyrgyzstan', 'ET': 'Ethiopia',
    'KE': 'Kenya', 'NI': 'Nicaragua', 'KY': 'Cayman Islands', 'UG': 'Uganda', 'LK': 'Sri Lanka', 'MV': 'Maldives',
    'SO': 'Somalia', 'CD': 'Democratic Republic of the Congo', 'SL': 'Sierra Leone', 'SM': 'San Marino',
    'LA': 'Laos', 'CG': 'Republic of the Congo', 'SR': 'Suriname', 'WS': 'Samoa', 'PY': 'Paraguay',
    'GF': 'French Guiana', 'DO': 'Dominican Republic', 'GP': 'Guadeloupe', 'MR': 'Mauritania', 'CI': 'Ivory Coast',
    'BJ': 'Benin', 'CU': 'Cuba', 'BT': 'Bhutan', 'PF': 'French Polynesia', 'GW': 'Guinea-Bissau', 'VE': 'Venezuela',
    'SV': 'El Salvador', 'ST': 'Sao Tome and Principe', 'FK': 'Falkland Islands', 'HN': 'Honduras', 'FJ': 'Fiji',
    'ZW': 'Zimbabwe', 'RW': 'Rwanda', 'NC': 'New Caledonia', 'BM': 'Bermuda', 'GU': 'Guam', 'MN': 'Mongolia',
    'NP': 'Nepal', 'TJ': 'Tajikistan', 'ZM': 'Zambia', 'BF': 'Burkina Faso', 'TZ': 'Tanzania', 'LC': 'Saint Lucia',
    'SD': 'Sudan', 'VC': 'Saint Vincent and the Grenadines', 'DJ': 'Djibouti', 'NE': 'Niger', 'GN': 'Guinea',
    'GA': 'Gabon', 'MM': 'Myanmar', 'FO': 'Faroe Islands', 'AG': 'Antigua and Barbuda', 'MZ': 'Mozambique',
    'BQ': 'Bonaire', 'GL': 'Greenland', 'AW': 'Aruba', 'VA': 'Vatican City', 'MQ': 'Martinique', 'BB': 'Barbados',
    'BS': 'Bahamas', 'JM': 'Jamaica', 'LR': 'Liberia', 'TT': 'Trinidad and Tobago', 'CM': 'Cameroon', 'CE': 'Central African Republic',
    'KN': 'Saint Kitts and Nevis', 'AO': 'Angola', 'TD': 'Chad', 'SX': 'Sint Maarten', 'PG': 'Papua New Guinea',
    'MG': 'Madagascar', 'BW': 'Botswana', 'BN': 'Brunei', 'BZ': 'Belize', 'TC': 'Turks and Caicos Islands',
    'CW': 'Curacao', 'GD': 'Grenada', 'TL': 'Timor-Leste', 'TG': 'Togo', 'GQ': 'Equatorial Guinea', 'YT': 'Mayotte',
    'PR': 'Puerto Rico', 'SS': 'South Sudan', 'MW': 'Malawi', 'CK': 'Cook Islands', 'MF': 'Saint Martin',
    'TM': 'Turkmenistan', 'VI': 'United States Virgin Islands', 'VG': 'British Virgin Islands', 'KM': 'Comoros',
    'HT': 'Haiti', 'PW': 'Palau', 'MS': 'Montserrat', 'AI': 'Anguilla', 'BI': 'Burundi', 'GY': 'Guyana'
}

In [68]:
len(ip_country_dict)

212

In [ ]:
# Compare the datasets and find unique IP address codes in the array that are not present as keys in the dictionary:

ip_addresses = set(array)  # Convert array to set
country_codes_set = set(ip_country_dict.keys())  # Get dictionary keys as set

unique_ips = ip_addresses - country_codes_set  # Find elements in array but not in dictionary keys

if unique_ips:
  print("Unique IP addresses not in dictionary:")
  print(unique_ips)
else:
  print("All IP addresses in the array are present as keys in the dictionary.")

Unique IP addresses not in dictionary:
{nan}

In [ ]:
gdp_per_capita_eur_dict = {
    'ES': 37316.7, 'GB': 41833.8, 'RO': 12710.7, 'FR': 43853.4, 'DE': 47938.5,
    'OM': 14340.6, 'IT': 36311.4, 'IL': 38530.8, 'AT': 47834.1, 'GR': 18680.4, 'NO': 67981.5,
    'AU': 51021, 'PT': 22955.4, 'NL': 57180.6, 'TR': 8624.7, 'CZ': 21448.8,
    'BG': 8805.6, 'PL': 15628.5, 'BE': 50067, 'SK': 18413.1, 'BR': 6618.6, 'CY': 28025.1,
    'KZ': 9670.5, 'IN': 2291.4, 'DK': 61821.9, 'SE': 54426.6, 'LU': 109163.7, 'KR': 31353.3,
    'KW': 28124.1, 'CH': 79108.2, 'LB': 4510.7, 'IE': 93051, 'EE': 21527.1, 'TN': 3393.9,
    'SA': 21005.1, 'CA': 46984.5, 'CN': 11544.3, 'JP': 38382.3, 'FI': 46281.6, 'AE': 39402,
    'AL': 5841.9, 'UA': 3187.8, 'MA': 3087, 'RU': 10373.4, 'HU': 17092.8, 'RS': 8669.7,
    'GE': 4879.8, 'HR': 15659.1, 'XK': 4190.4, 'SI': 25478.1, 'IQ': 4168.8, 'AR': 8118.9,
    'NZ': 41063.4, 'DZ': 3327.3, 'BY': 5855.4, 'LV': 19066.5, 'TW': 31140.9, 'JO': 3834,
    'ID': 3870, 'EG': 3231.9, 'ME': 7632, 'AF': 464.4, 'MX': 9477, 'BO': 3213,
    'NG': 1844.1, 'US': 63032.4, 'PH': 3195.9, 'LT': 21366.9, 'PK': 1309.5,
    'UZ': 1758.6, 'SG': 63666.9, 'CO': 6180.3, 'UY': 15967.8, 'MC': 155700, 'MT': 29303.1,
    'AM': 4219.2, 'IS': 69146.1, 'BA': 6165, 'BH': 22943.7, 'TH': 7074,
    'MY': 10073.7, 'AD': 44900.4, 'VN': 3766.5, 'CR': 11781, 'AZ': 4782.6, 'LI': 162204.3,
    'IR': 2486.7, 'LY': 3606.3, 'YE': 741.6, 'MD': 4141.8, 'GH': 2201.4, 'PS': 3465.9,
    'SC': 13797, 'JE': 51840, 'ZA': 5625.9, 'GM': 684.9, 'SY': 1141.2, 'CV': 3182.4,
    'QA': 55208.7, 'BD': 1834.2, 'CL': 14157.9, 'PA': 11999.8, 'IM': 80055, 'MK': 6141.6,
    'KH': 1405.8, 'PE': 6546.6, 'EC': 5617.8, 'GT': 4835.7, 'SN': 1489.5, 'RE': 22314.6,
    'GG': 60300, 'MU': 10635.3, 'ML': 809.1, 'GI': 83034.9, 'KG': 1112.4, 'ET': 857.7,
    'KE': 1859.4, 'NI': 2064.6, 'KY': 76725, 'UG': 742.5, 'LK': 3467.7, 'MV': 9471.3,
    'SO': 394.2, 'CD': 505.8, 'SL': 470.7, 'SM': 55187.1, 'LA': 2372.4, 'CG': 2143.8, 'SR': 4352.4,
    'WS': 3930.3, 'PY': 4956.3, 'GF': 21075.3, 'DO': 7893, 'GP': 21758.4, 'MR': 1461.6, 'CI': 2475.9,
    'BJ': 1227.6, 'CU': 8883, 'BT': 3118.5, 'PF': 16650, 'GW': 720.9, 'VE': 288.9,
    'SV': 4023, 'ST': 1955.7, 'FK': 72000, 'HN': 2397.6, 'FJ': 5961.6,
    'ZW': 1342.8, 'RW': 843.3, 'NC': 32220, 'BM': 96957, 'GU': 31761, 'MN': 4115.7,
    'NP': 1209.6, 'TJ': 773.1, 'ZM': 1013.4, 'BF': 825.3, 'TZ': 1047.6, 'LC': 9219.6,
    'SD': 1470.6, 'VC': 6655.5, 'DJ': 2761.2, 'NE': 522.9, 'GN': 850.5,
    'GA': 7128.9, 'MM': 1404.9, 'FO': 53675.1, 'AG': 15437.7, 'MZ': 438.3,
    'BQ': 21150, 'GL': 48600, 'AW': 23397.3, 'VA': 76500, 'MQ': 21775.8, 'BB': 16882.2,
    'BS': 29871, 'JM': 4527.9, 'LR': 550.8, 'TT': 14395.5, 'CM': 1515.6, 'CE': 451.8,
    'KN': 17208, 'AO': 2998.8, 'TD': 598.5, 'SX': 21330, 'PG': 2426.4,
    'MG': 470.7, 'BW': 6738.3, 'BN': 27978.3, 'BZ': 4443.3, 'TC': 26550,
    'CW': 20070, 'GD': 9037.8, 'TL': 1677.6, 'TG': 810, 'GQ': 8034.3, 'YT': 8444.7,
    'PR': 29406.6, 'SS': 202.5, 'MW': 562.5, 'CK': 14809.5, 'MF': 21775.8,
    'TM': 6252.3, 'VI': 34528.5, 'VG': 38070, 'KM': 1296, 'HT': 1342.8, 'PW': 14356.8,
    'MS': 11070, 'AI': 18270, 'BI': 215.1, 'GY': 12591
}

In [ ]:
# Create a new column in the df with the GDP per capita values (based on "UserCountryCode")

df['GDP_per_capita_EUR'] = df['UserCountryCode'].map(gdp_per_capita_eur_dict)

df

,flightWeek,OriginAirport,DestinationAirport,OriginCountry,DestinationCountry,mainCarrier,isConnectingFlight,isEWRoute,Market,UserCountryCode,...,TripLengthNights,TravelHorizonDays,RedirectsCount,Revenue,Segments,ODPax,TripPax,weekOfYear,Average_FlightFare,GDP_per_capita_EUR
0,2024-W24,ALC,OPO,ES,PT,FR,0,0,ES,ES,...,4.0,41,9,3914.87,66,18,33,2024-W18,59.316212,37316.7
1,2024-W31,LTN,JMK,GB,GR,U2,1,0,UK,GB,...,4.0,89,1,610.91,4,2,2,2024-W18,152.727500,41833.8
2,2024-W18,TSR,BCN,RO,ES,H4,1,0,UK,RO,...,3.0,3,2,711.19,4,4,2,2024-W18,177.797500,12710.7
3,2024-W30,NTE,PMO,FR,IT,TO,0,0,FR,FR,...,14.0,78,4,4406.40,30,8,15,2024-W18,146.880000,43853.4
4,2024-W31,FRA,MLA,DE,MT,LH,0,0,DE,DE,...,7.0,93,15,10398.57,58,30,29,2024-W18,179.285690,47938.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2024-W31,BLQ,SKP,IT,MK,W6,0,0,AU,AU,...,NaN,92,2,483.27,4,2,4,2024-W18,120.817500,51021.0
1048571,2024-W29,BRU,KGS,BE,GR,SN,0,0,BE,BE,...,7.0,80,1,1539.60,4,2,2,2024-W18,384.900000,50067.0
1048572,2024-W22,GOT,MHD,SE,IR,TK,1,0,SE,SE,...,30.0,33,1,3551.05,6,2,3,2024-W18,591.841667,54426.6
1048573,2024-W34,MXP,BEG,IT,RS,JU,0,0,IT,AT,...,NaN,115,1,90.11,1,1,1,2024-W18,90.110000,47834.1
1048574,2024-W21,NRN,PSR,DE,IT,FR,0,0,DE,DE,...,4.0,18,1,196.98,6,2,3,2024-W18,32.830000,47938.5

In [ ]:

def carrier_code_simple(carrier):
    if carrier == "EW":
        return "EW"
    elif carrier == "E6":
        return "EW"
    elif carrier == "4X":
        return "EW"
    else:
        return carrier

# Apply the function to the df (I don't like using apply)

df['mainCarrier'] = df['mainCarrier'].apply(carrier_code_simple)

df[df['mainCarrier'] == 'EW']

,flightWeek,OriginAirport,DestinationAirport,OriginCountry,DestinationCountry,mainCarrier,isConnectingFlight,isEWRoute,Market,UserCountryCode,...,TripLengthNights,TravelHorizonDays,RedirectsCount,Revenue,Segments,ODPax,TripPax,weekOfYear,Average_FlightFare,GDP_per_capita_EUR
15,2024-W23,DUS,LHR,DE,GB,EW,0,1,UK,GB,...,NaN,39,2,459.59,3,2,3,2024-W18,153.196667,41833.8
38,2024-W22,STR,LHR,DE,GB,EW,0,1,DE,DE,...,3.0,28,7,4408.41,26,14,13,2024-W18,169.554231,47938.5
63,2024-W28,DUS,AGP,DE,ES,EW,0,1,DE,NL,...,34.0,69,3,5124.48,30,6,15,2024-W18,170.816000,57180.6
153,2024-W18,EDI,CGN,GB,DE,EW,0,1,DE,GB,...,9.0,1,1,213.77,2,2,1,2024-W18,106.885000,41833.8
154,2024-W39,CGN,LIS,DE,PT,EW,0,1,DE,DE,...,5.0,145,1,581.39,4,2,2,2024-W18,145.347500,47938.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048420,2024-W22,DUS,PMI,DE,ES,EW,1,1,DE,DE,...,3.0,31,1,212.11,2,2,1,2024-W18,106.055000,47938.5
1048494,2024-W43,MAN,DUS,GB,DE,EW,0,1,UK,GB,...,5.0,176,1,725.83,12,2,6,2024-W18,60.485833,41833.8
1048513,2024-W19,DUS,MUC,DE,DE,EW,0,1,DE,DE,...,1.0,11,2,457.59,4,4,2,2024-W18,114.397500,47938.5
1048524,2024-W34,VIE,HAM,AT,DE,EW,0,1,DE,DE,...,NaN,114,1,149.67,1,1,1,2024-W18,149.670000,47938.5
1048535,2024-W19,HAM,MAN,DE,GB,EW,0,1,UK,GB,...,NaN,9,1,85.19,1,1,1,2024-W18,85.190000,41833.8